import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '/styles/globals.css'
import Link from 'next/dist/client/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="bg-blue-700 p-4">
        <ul className="flex space-x-10 justify-end">
          <li><Link href="/" className="text-white hover:bg-mint-100 p-4 hover:text-black">Home</Link></li>
          <li><Link href='/shop' className="text-white hover:underline">Shop</Link></li>
          <li><Link href="/d_products" className="text-white hover:underline">Dogs</Link></li>
          <li><Link href="/c_products" className="text-white hover:underline">Cat</Link></li>
          <li><Link href="/f_products" className="text-white hover:underline">Fish</Link></li>
          <li><Link href="/r_products" className="text-white hover:underline">Reptiles</Link></li>
          <li><Link href="/b_products" className="text-white hover:underline">Birds</Link></li>
          <li><Link href="/" className="text-white hover:underline">About Us</Link></li>
          <li><Link href="/" className="text-white hover:underline">Sign In</Link></li>
        </ul>
      </nav>

      
        {children}</body>
    </html>
  )
}